DROP TABLE IF EXISTS MAQUINAS_REGISTRADORAS;
CREATE TABLE MAQUINAS_REGISTRADORAS (
    Codigo INT PRIMARY KEY AUTO_INCREMENT,
    Piso INT
);
DROP TABLE IF EXISTS CAJEROS;
CREATE TABLE CAJEROS (
    Codigo INT PRIMARY KEY AUTO_INCREMENT,
    NomApels NVARCHAR(255)
);
DROP TABLE IF EXISTS PRODUCTOS;
CREATE TABLE PRODUCTOS (
    Codigo INT PRIMARY KEY AUTO_INCREMENT,
    Nombre NVARCHAR(100),
    Precio INT
);
DROP TABLE IF EXISTS VENTA;
CREATE TABLE VENTA (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Cajero INT,
    Maquina INT,
    Producto INT,
    FOREIGN KEY (Cajero) REFERENCES CAJEROS(Codigo),
    FOREIGN KEY (Maquina) REFERENCES MAQUINAS_REGISTRADORAS(Codigo),
    FOREIGN KEY (Producto) REFERENCES PRODUCTOS(Codigo)
);


