-- Tabla PROFESORES
CREATE TABLE PROFESORES (
    NOMBRE VARCHAR(50),
    APELLIDO1 VARCHAR(50),
    APELLIDO2 VARCHAR(50),
    DNI VARCHAR(8) PRIMARY KEY,
    DIRECCION VARCHAR(100),
    TITULO VARCHAR(100),
    GANA FLOAT
);
-- Tabla ALUMNOS
CREATE TABLE ALUMNOS (
    NOMBRE VARCHAR(50),
    APELLIDO1 VARCHAR(50),
    APELLIDO2 VARCHAR(50),
    DNI VARCHAR(8) PRIMARY KEY,
    DIRECCION VARCHAR(100),
    SEXO CHAR(1),
    FECHA_NACIMIENTO DATE,
    CURSO INT,
    FOREIGN KEY (CURSO) REFERENCES CURSOS(COD_CURSO)
);

-- Tabla CURSOS
CREATE TABLE CURSOS (
    NOMBRE_CURSO VARCHAR(100),
    COD_CURSO INT PRIMARY KEY,
    DNI_PROFESOR VARCHAR(8),
    MAX_ALUMNOS INT,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    NUM_HORAS INT,
    FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESORES(DNI)
);
