CREATE TABLE FABRICANTES (
    FabricanteID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre NVARCHAR(100)
);

CREATE TABLE ARTICULOS (
    Codigo INT AUTO_INCREMENT PRIMARY KEY,
    Nombre NVARCHAR(100),
    Precio INT,
    FabricanteID INT,
    FOREIGN KEY (FabricanteID) REFERENCES FABRICANTES(FabricanteID)
);

