CREATE TABLE ALMACENES (
    Codigo INT AUTO_INCREMENT PRIMARY KEY,
    Lugar NVARCHAR(100),
    Capacidad INT
);
CREATE TABLE CAJAS (
    NumReferencia CHAR(5) PRIMARY KEY,
    Contenido NVARCHAR(100),
    Valor INT,
    Almacen INT,
    FOREIGN KEY (Almacen) REFERENCES ALMACENES(Codigo)
);
